#!/bin/sh

# Preparation
mkdir "${HOME}/.config" 2> /dev/null

# Setup GTK 2
ln -sf "${PWD}/.gtkrc-2.0" "${HOME}/.gtkrc-2.0"

# Setup GTK 3
ln -sf "${PWD}/gtk-3.0" -t "${HOME}/.config/"

# Setup GTK 4
ln -sf "${PWD}/gtk-4.0" -t "${HOME}/.config/"
