#!/bin/sh

printf "Type the desired image format: "
read -r myformat

printf "Type the file name (without extension): "
read -r myfile

printf "Type the desired mode [ Lineart Gray Color ]: "
read -r mymode

scanimage -d epson2 --format="$myformat" --mode "$mymode" -p > "${myfile}"."${myformat}"
